default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
default_language_version:
  python: python3.12
default_stages: [pre-commit, pre-merge-commit, pre-push, manual]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        types_or: [python]
