name: Deploy Shiny App

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/deploy_app.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Export and Commit Shinylive App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12' 

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "0.8.9"

      - name: Synchronize environment
        id: uv-sync
        run: uv sync --locked

      - name: Export shinylive
        id: export-shinylive
        run: uv run shinylive export app docs 
    
      - name: Commit docs
        id: commit-docs
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "app: exported to docs $(date +'%Y-%m-%d %H:%M:%S')"
          file_pattern: "docs/**"
          disable_globbing: true
          branch: main
