name: Scrape & Deploy Treasury Bills App

on:
  schedule:
    # According to https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_bill_rates
    # Market quotations are obtained at approximately 3:30 PM each business day by the Federal Reserve Bank of New York
    - cron: '0 22 * * 1-5'  # Run at 10 PM UTC, Monday to Friday (5 PM EST weekdays)
  pull_request:
    branches:
      - main
    paths:
      - 'src/tbills.py'
      - 'main.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/scrape_deploy_app.yml'
      - 'app/**'
  push:
    branches:
      - main
    paths:
      - 'src/tbills.py'
      - 'main.py'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/scrape_deploy_app.yml'
      - 'app/**'
  workflow_dispatch:

permissions:
  id-token: write # Required for requesting the Json Web Token (JWT)
  contents: write  # Required for actions/checkout and git commits

jobs:
  scrape:
    name: Scrape US Treasury Bills Data
    runs-on: ubuntu-latest
    outputs:
      did_commit: ${{ steps.commit-data.outputs.changes_detected }}
      commit_sha:  ${{ steps.commit-data.outputs.commit_hash }}

    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials from OIDC
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          role-session-name: daily-scrape-session
          output-credentials: true

      - name: Add profile credentials to ~/.aws/credentials 
        id: add-profile-credentials
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile admin
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile admin
          aws configure set aws_session_token ${{ env.AWS_SESSION_TOKEN }} --profile admin
        env:
            AWS_ACCESS_KEY_ID: ${{ steps.configure-aws-credentials.outputs.aws-access-key-id }}
            AWS_SECRET_ACCESS_KEY: ${{ steps.configure-aws-credentials.outputs.aws-secret-access-key }}
            AWS_SESSION_TOKEN: ${{ steps.configure-aws-credentials.outputs.aws-session-token }}

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12' 

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "0.8.9"

      - name: Synchronize environment
        id: uv-sync
        run: uv sync --locked

      - name: Run scraper
        id: run-scraper
        run: uv run python3 main.py
        env:
            TABLE_NAME: ${{ secrets.TABLE_NAME }}
            ATHENA_WORKGROUP: ${{ secrets.ATHENA_WORKGROUP }}
            ATHENA_OUTPUT_S3: ${{ secrets.ATHENA_OUTPUT_S3 }}
            SUBCATALOG: ${{ secrets.SUBCATALOG }}
            DATABASE: ${{ secrets.DATABASE }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Slack Notification
        id: slack-notify
        if: always() 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}  
          SLACK_COLOR: ${{ job.status }}                
          SLACK_TITLE: "Daily US Treasury Yield: ${{ github.workflow }} @ ${{ github.ref_name }}"
          SLACK_MESSAGE_ON_SUCCESS: "✅ Scrape completed for `${{ github.ref_name }}` — run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          SLACK_MESSAGE_ON_FAILURE: "❌ Scrape FAILED for `${{ github.ref_name }}` — run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          SLACK_MESSAGE_ON_CANCEL:  "⚠️ Scrape CANCELLED for `${{ github.ref_name }}` — run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          SLACK_USERNAME: "gh-bot"
          SLACK_ICON_EMOJI: ":robot_face:"
          SLACKIFY_MARKDOWN: "true"
      
      - name: Commit data
        id: commit-data
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "scraper: saved data to s3 table bucket ${{ github.run_id }} - ${{ github.run_number }}"
          file_pattern: "app/data/**"
          disable_globbing: true
          branch: main
          # Ensure commits are authored solely by the bot
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

  deploy:
    name: Export and Commit Shinylive App
    runs-on: ubuntu-latest
    needs: scrape
    # Only run deploy if scrape succeeded AND a commit actually happened
    if: ${{ success() && needs.scrape.outputs.did_commit == 'true' }}

    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          # Build from the exact commit that was created by the scrape job (fallback to current SHA if empty)
          ref: ${{ needs.scrape.outputs.commit_sha || github.sha }}

      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12' 

      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "0.8.9"

      - name: Synchronize environment
        id: uv-sync
        run: uv sync --locked

      - name: Export shinylive
        id: export-shinylive
        run: uv run shinylive export app docs 
    
      - name: Commit docs
        id: commit-docs
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "app: exported to docs ${{ github.run_id }} - ${{ github.run_number }}"
          file_pattern: "docs/**"
          disable_globbing: true
          branch: main
          # Ensure commits are authored solely by the bot
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
